
spring:
  datasource:
#    url: jdbc:oracle:thin:@jakedb37_high?TNS_ADMIN=C:/opt/oralceCloud/JAKEDB
    url: jdbc:oracle:thin:@jakedb37_high?TNS_ADMIN=/users/heeweon/Dev/dongyoung/OracleCloudWallet/JAKEDB
    username: JPASTUDY
    password: Oracle12345678
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6


